meta:
  version: 2
  flow: Classic
  substituting_steps:
    Checker.YosysSynthChecks: null
    
    # Allow assignments for porb_h
    Checker.NetlistAssignStatements: null
    
    # For debugging
    +OpenROAD.GeneratePDN: Magic.StreamOut
    
    # Ignore disconnected pins
    Checker.DisconnectedPins: null
    
    # TODO reenable again?
    OpenROAD.IRDropReport: null
    
    # Not needed
    Magic.WriteLef: null
    Odb.CheckDesignAntennaProperties: null
    
    # KLayout doesn't streamout the OpenRAM (?)
    KLayout.StreamOut: null
    KLayout.XOR: null
    
    # Magic has issues with the OpenRAM
    Magic.DRC: null
    
    # We run LVS manually
    Netgen.LVS: null
    
    # Some macros overlap on purpose
    Checker.IllegalOverlap: null

DESIGN_NAME: panamax_fpga_top
VERILOG_FILES:
- dir::src/panamax_fpga_top.v
- dir::src/panamax_fpga_core.sv
- dir::ip/fabulous_fabric/fabric_sky130/rtl/fabric_wrapper.sv
- dir::ip/fabulous_fabric/rtl/fabric_config.sv
- dir::ip/fabulous_fabric/rtl/fabric_spi_receiver.sv
- dir::ip/fabulous_fabric/rtl/fabric_spi_controller.sv

DEDUPLICATE_CORNERS: true

# Magic streamout: don't blackbox macros
MAGIC_MACRO_STD_CELL_SOURCE: PDK

IGNORE_DISCONNECTED_MODULES:
    - manual_routing
    - sky130_ef_ip__adc3v_12bit
    - sky130_ef_ip__rdac3v_8bit

# Prevent porb_h mangling
SYNTH_DIRECT_WIRE_BUFFERING: False
SYNTH_WRITE_NOATTR: False

# Ignores don't touch directive
PL_TIME_DRIVEN: False

# Clock
CLOCK_NET: xclk
CLOCK_PORT: gpio8_0_in
CLOCK_PERIOD: 20

# SDC
FALLBACK_SDC_FILE: dir::base.sdc

# CTS
CTS_OBSTRUCTION_AWARE: true
CTS_CLK_MAX_WIRE_LENGTH: 1200
CTS_SINK_CLUSTERING_SIZE: 25 # default 25
CTS_SINK_CLUSTERING_MAX_DIAMETER: 60 # default 50

# Routing
GRT_ALLOW_CONGESTION: true
RT_CLOCK_MAX_LAYER: met4
#RT_MAX_LAYER: met4
#DRT_MAX_LAYER: met4

# Resizer
RSZ_DONT_TOUCH_RX: porb_h|_enable_h
DESIGN_REPAIR_BUFFER_INPUT_PORTS: false
DESIGN_REPAIR_BUFFER_OUTPUT_PORTS: false

# Overfix hold violations
PL_RESIZER_HOLD_SLACK_MARGIN: 0.2

VDD_NETS:
- DVPWR

GND_NETS:
- DVGND

FP_PDN_CFG: dir::pdn_cfg.tcl

FP_PDN_VWIDTH: 2.0
FP_PDN_HWIDTH: 5.0
FP_PDN_VSPACING: 1.7
FP_PDN_HSPACING: 1.7
FP_PDN_VPITCH: 55
FP_PDN_HPITCH: 110

FP_PDN_CORE_RING: true
FP_PDN_CORE_RING_VWIDTH: 8
FP_PDN_CORE_RING_HWIDTH: 8

FP_PDN_CORE_RING_VOFFSET: 2
FP_PDN_CORE_RING_HOFFSET: 2

# Floorplanning
FP_SIZING: absolute
DIE_AREA:  [   0.00,   0.00, 3170.300, 4770.650 ]
CORE_AREA: [  20.00,   20.00, 3150.300, 4750.650 ]

FP_DEF_TEMPLATE: dir::ip/panamax_core_pins/def/panamax_core_pins.def
FP_TEMPLATE_MATCH_MODE: permissive
#FP_TEMPLATE_COPY_POWER_PINS: True

PL_TARGET_DENSITY_PCT: 20 # TODO

FP_OBSTRUCTIONS:
# SIO
- [2651.15, 0.00, 3170.30, 55.215]
# ADC/DAC area
- [790, 0.00, 1720, 290]

PDN_OBSTRUCTIONS:
# SIO
- [met1, 2661.15, 0.00, 3141.15, 46.715]
- [met2, 2661.15, 0.00, 3141.15, 46.715]
- [met3, 2661.15, 0.00, 3141.15, 46.715]
- [met4, 2661.15, 0.00, 3141.15, 46.715]
- [met5, 2661.15, 0.00, 3141.15, 46.715]
# ADC/DAC area
- [met4, 790, 0.00, 1720, 290] #[met4, 800, 20, 1700, 270]
- [met5, 790, 0.00, 1720, 290] #[met5, 800, 20, 1700, 270]
# Logo
- [met5, 2665, 120, 3070, 265]

# Power connections

# Bottom
- [met4, 26.45, 0, 100.66, 20]

- [met4, 931.45, 0, 1005.66, 20]

- [met4, 1611.45, 0, 1685.66, 20]

- [met4, 2551.45, 0, 2625.66, 20]

# Top
- [met4, 3085.65, 4750.65, 3147.9, 4770.65]

- [met4, 2375.64, 4750.65, 2449.905, 4770.65]

- [met4, 725.65, 4750.65, 799.85, 4770.65]

- [met4, 27.65, 4750.65, 89.85, 4770.65]

ROUTING_OBSTRUCTIONS:
# SIO
- [met1, 2661.15, 0.00, 3141.15, 46.715]
- [met2, 2661.15, 0.00, 3141.15, 46.715]
- [met3, 2661.15, 0.00, 3141.15, 46.715]
- [met4, 2661.15, 0.00, 3141.15, 46.715]
- [met5, 2661.15, 0.00, 3141.15, 46.715]
# ADC/DAC area
#- [met4, 800, 0.00, 1700, 270]
# Logo
- [met5, 2665, 120, 3070, 265]


# Power connections

# Bottom
- [met3, 26.45, 0, 100.66, 20]
- [met4, 26.45, 0, 100.66, 20]

- [met3, 931.45, 0, 1005.66, 20]
- [met4, 931.45, 0, 1005.66, 20]

- [met3, 1611.45, 0, 1685.66, 20]
- [met4, 1611.45, 0, 1685.66, 20]

- [met3, 2551.45, 0, 2625.66, 20]
- [met4, 2551.45, 0, 2625.66, 20]

# Right
- [met3, 3150.3, 584.8, 3170.3, 659]

- [met3, 3150.3, 2184.8, 3170.3, 2259.01]

- [met3, 3150.3, 3487.8, 3170.3, 3562]

- [met3, 3150.3, 4527.8, 3170.3, 4602.01]

# Top
- [met3, 3085.65, 4750.65, 3147.9, 4770.65]
- [met4, 3085.65, 4750.65, 3147.9, 4770.65]

- [met3, 2375.64, 4750.65, 2449.905, 4770.65]
- [met4, 2375.64, 4750.65, 2449.905, 4770.65]

- [met3, 725.65, 4750.65, 799.85, 4770.65]
- [met4, 725.65, 4750.65, 799.85, 4770.65]

- [met3, 27.65, 4750.65, 89.85, 4770.65]
- [met4, 27.65, 4750.65, 89.85, 4770.65]

# Left
- [met3, 0, 4537, 20, 4611.2]

- [met3, 0, 3497, 20, 3571.2]

- [met3, 0, 2199, 20, 2273.2]

- [met3, 0, 589, 20, 663.2]

# Magic: Use LEF/DEF to prevent error on the SRAMs
MAGIC_DRC_USE_GDS: False

MACROS:
  eFPGA:
    gds:
      - dir::ip/fabulous_fabric/fabric_sky130/macro/sky130A/gds/eFPGA.gds
    lef:
      - dir::ip/fabulous_fabric/fabric_sky130/macro/sky130A/lef/eFPGA.lef
    nl:
      - dir::ip/fabulous_fabric/fabric_sky130/macro/sky130A/nl/eFPGA.nl.v
    pnl:
      - dir::ip/fabulous_fabric/fabric_sky130/macro/sky130A/pnl/eFPGA.pnl.v
    spef:
      "min_*":
        - dir::ip/fabulous_fabric/fabric_sky130/macro/sky130A/spef/min/eFPGA.min.spef
      "nom_*":
        - dir::ip/fabulous_fabric/fabric_sky130/macro/sky130A/spef/nom/eFPGA.nom.spef
      "max_*":
        - dir::ip/fabulous_fabric/fabric_sky130/macro/sky130A/spef/max/eFPGA.max.spef
    instances: 
      panamax_fpga_core.fabric_wrapper.eFPGA:
        # Height should be multiple of 0.68 (met3 pitch)
        # Width should be multiple of 0.46 (met2 pitch)
        location: [237.8, 349.52]
        orientation: N

  sky130_ef_ip__simple_por4x:
    gds:
      - dir::ip/sky130_ef_ip__simple_por/gds/sky130_ef_ip__simple_por4x.gds.gz
    lef:
      - dir::ip/sky130_ef_ip__simple_por/lef/sky130_ef_ip__simple_por4x.lef
    pnl:
      - dir::ip/sky130_ef_ip__simple_por/verilog/simple_por4x.v
    instances: 
      simple_por4x:
        location: [1613, 100]
        orientation: S

  res_div:
    gds:
      - dir::ip/res_div/gds/res_div.gds.gz
    lef:
      - dir::ip/res_div/lef/res_div.lef
    nl:
      - dir::ip/res_div/gl/res_div.v
    instances:
      res_div0:
        location: [813, 240]
        orientation: W
      res_div1:
        location: [1123, 240]
        orientation: W

  sky130_ef_ip__adc3v_12bit:
    gds:
    - dir::ip/sky130_ef_ip__adc3v_12bit/gds/sky130_ef_ip__adc3v_12bit.gds.gz
    lef:
    - dir::ip/sky130_ef_ip__adc3v_12bit/lef/sky130_ef_ip__adc3v_12bit.lef
    instances:
      adc0:
        location: [ 800, 30 ]
        orientation: W
      adc1:
        location: [ 1110, 30 ]
        orientation: W
    nl:
    - dir::ip/sky130_ef_ip__adc3v_12bit/verilog/sky130_ef_ip__adc3v_12bit.v

  sky130_ef_ip__rdac3v_8bit:
    gds:
    - dir::ip/sky130_ef_ip__rdac3v_8bit/gds/sky130_ef_ip__rdac3v_8bit.gds.gz
    lef:
    - dir::ip/sky130_ef_ip__rdac3v_8bit/lef/sky130_ef_ip__rdac3v_8bit.lef
    instances:
      dac0:
        location: [ 1418, 55 ]
        orientation: S
      dac1:
        location: [ 1518, 55 ]
        orientation: S
    nl:
    - dir::ip/sky130_ef_ip__rdac3v_8bit/verilog/sky130_ef_ip__rdac3v_8bit.v

  sky130_sram_1kbyte_1rw1r_32x256_8:
    gds:
      - pdk_dir::libs.ref/sky130_sram_macros/gds/sky130_sram_1kbyte_1rw1r_32x256_8.gds
    lef:
      - pdk_dir::libs.ref/sky130_sram_macros/lef/sky130_sram_1kbyte_1rw1r_32x256_8.lef
    nl:
      - pdk_dir::libs.ref/sky130_sram_macros/verilog/sky130_sram_1kbyte_1rw1r_32x256_8.v
    #lib:
    #  "*":
    #    - pdk_dir::libs.ref/sky130_sram_macros/lib/sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.lib
    instances: 
      panamax_fpga_core.fabric_wrapper.bram_0:
        location: [2635, 4100]
        orientation: N
      panamax_fpga_core.fabric_wrapper.bram_1:
        location: [2635, 3580]
        orientation: N
      panamax_fpga_core.fabric_wrapper.bram_2:
        location: [2635, 3060]
        orientation: N
      panamax_fpga_core.fabric_wrapper.bram_3:
        location: [2635, 2540]
        orientation: N
      panamax_fpga_core.fabric_wrapper.bram_4:
        location: [2635, 2020]
        orientation: N
      panamax_fpga_core.fabric_wrapper.bram_5:
        location: [2635, 1500]
        orientation: N
      panamax_fpga_core.fabric_wrapper.bram_6:
        location: [2635, 980]
        orientation: N
      panamax_fpga_core.fabric_wrapper.bram_7:
        location: [2635, 460]
        orientation: N

  manual_routing:
    gds:
      - dir::ip/manual_routing/gds/manual_routing.gds.gz
    lef:
      - dir::ip/manual_routing/lef/manual_routing.lef
    nl:
      - dir::ip/manual_routing/gl/manual_routing.v
    instances:
      manual_routing:
        location: [0, 0]
        orientation: N

PDN_MACRO_CONNECTIONS:
  - "panamax_fpga_core.fabric_wrapper.eFPGA DVPWR DVGND VPWR VGND"
  - "panamax_fpga_core.fabric_wrapper.bram_0 DVPWR DVGND vccd1 vssd1"
  - "panamax_fpga_core.fabric_wrapper.bram_1 DVPWR DVGND vccd1 vssd1"
  - "panamax_fpga_core.fabric_wrapper.bram_2 DVPWR DVGND vccd1 vssd1"
  - "panamax_fpga_core.fabric_wrapper.bram_3 DVPWR DVGND vccd1 vssd1"
  - "panamax_fpga_core.fabric_wrapper.bram_4 DVPWR DVGND vccd1 vssd1"
  - "panamax_fpga_core.fabric_wrapper.bram_5 DVPWR DVGND vccd1 vssd1"
  - "panamax_fpga_core.fabric_wrapper.bram_6 DVPWR DVGND vccd1 vssd1"
  - "panamax_fpga_core.fabric_wrapper.bram_7 DVPWR DVGND vccd1 vssd1"
