// Auto-generated by OpenLane
module dll(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input resetb,
  input enable,
  input osc,
  input[7:0] div,
  input dco,
  input[25:0] ext_trim,
  output[1:0] clockp
);
endmodule
