meta:
  version: 2
  flow: Classic

DESIGN_NAME: dll
VERILOG_FILES:
- dir::src/dll.v

FP_PDN_MULTILAYER: false
RT_MAX_LAYER: met4

CLOCK_PORT: ""
RUN_CTS: False

# Synthesis
MAX_FANOUT_CONSTRAINT: 7
SYNTH_ABC_BUFFERING: True # TODO
SYNTH_SIZING: False

ERROR_ON_SYNTH_CHECKS: False

PNR_SDC_FILE: dir::base.sdc
SIGNOFF_SDC_FILE: dir::base.sdc

SYNTH_EXCLUDED_CELL_FILE: dir::no_synth.list

## Floorplan
FP_PIN_ORDER_CFG: dir::pin_order.cfg

FP_SIZING: absolute
DIE_AREA: [0, 0, 135, 110] #[0, 0, 100, 75]

TOP_MARGIN_MULT: 2
BOTTOM_MARGIN_MULT: 2

DIODE_PADDING: 0
DPL_CELL_PADDING: 2

## PDN 
FP_PDN_VPITCH: 40
FP_PDN_HPITCH: 40
FP_PDN_HOFFSET: 16.41
FP_PDN_HSPACING: 18.4
FP_PDN_VSPACING: 18.4

## Placement
RUN_POST_GPL_DESIGN_REPAIR: False
RUN_POST_CTS_RESIZER_TIMING: False
PL_TARGET_DENSITY_PCT: 68

## Routing 
RUN_POST_GRT_RESIZER_TIMING: False
GRT_ADJUSTMENT: 0

FP_PDN_SKIPTRIM: True
